### ISSUE TITLE
Manual secret entry (no camera)

### ISSUE THREAD

**Issue by RobGitH** [freeotp/freeotp-ios#186] opened 2020-07-09 18:40 UTC
Thanks to the team for a very robust OTP tool. I have been using the earlier release and prefer to enter the secret manually, not via the camera QR code. In the latest release (which looks very nice by the way), that functionality is no longer available. 

Are there plans to add this functionality of manual secret key entry back ? I find it very useful to manually enter the secret and do not typically use the QR method.

Thanks again for a great product, hoping this functionality will become available again,

**Comment by Githubuxer** [comment] 2020-07-12 10:29
Wondering about if manual entry will be added back as well, as multiple occasions have not been able to setup 2FA while on mobile device and have to wait until using multiple devices to use QR scanner.

**Comment by Githubuxer** [comment] 2020-07-28 10:53
Ran into this issue again on iOS. Can not activate 2FA on mobile device, because no manual entry. There is nowhere to paste the code.

Why do we have to wait until have desktop and mobile device to initiate 2FA?

**Comment by justin-stephenson** [comment] 2020-07-28 12:56
Hello,

There are currently no plans at the moment to add the manual entry back.

If your 2FA server provide an `otpauth://` URI similar to:

```otpauth://totp/ACME%20Co:john.doe@email.com?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=ACME%20Co&algorithm=SHA1&digits=6&period=30```

The link should be pressable which will forward the URI to FreeOTP, if it's not a clickable link you can copy the text to an App like Notes and then press the link. This method also works for QR codes provided by the 2FA server by doing a press + hold gesture of the image to copy the token URI string value.

**Comment by Githubuxer** [comment] 2020-07-28 13:24
Is there a particular reason for that?

I just tried to copy paste that text and insert secret but is very difficult on iOS, as when you are trying to edit the link, it’s trying to follow instead of letting me insert.

Ultimately it was too frustrating and I just used Google Authenticator for that one..

Wealthsimple Trade is an app only, not desktop dashboard and there is no barcode image, only text key.

**Comment by pierr0t** [comment] 2020-11-18 09:50
Hello,

Same here, the Webmin server panel provides a QRCode that does not work (FreeOTP says Invalid URL, I will report that to the Webmin team) so manual entry was up to the previous FreeOTP version the only solution, I never thought that this feature would be removed ... I had to install Authy in order to regain access to some servers.

Trying the provided method is, as mentionned previously, very frustrating and in any case, my url being invalid it does not work. It is however worth noticing that **Authy did work with the same QRcode** that is considered invalid by FreeOTP ... 
so I'm not sure where the problem is, FreeOTP or Webmin ?

Pierre

**Comment by Githubuxer** [comment] 2020-11-18 13:58
It would be perfect to have a plus sign (+) in the top bar to add back manual entry, it is ideal to only have 1 2FA app instead of 2.

**Comment by pierr0t** [comment] 2020-11-18 14:00
Yes the way it was before if I recall correctly :-)

**Comment by kapdap** [comment] 2021-01-02 23:48
Please add option to manually add secrets.

**Comment by eloquence** [comment] 2021-09-02 23:52
Hi folks, on the SecureDrop project, we've found that adding secrets manually can be important in practice for a few reasons:

- it can be tricky to render QR codes reliably in a terminal window
- in Tor Browser in particular, QR codes rendered as SVG images may not be displayed at all, depending on a user's security settings
- administrators who assist users remotely may need to securely disseminate 2FA secrets to the user, which is more cumbersome when dealing with QR images
- as noted above, users may encounter any number of technical issues when scanning the image

Providing direct secret entry also seems important for accessibility reasons, e.g., to support vision-impaired users.

If y'all have bandwidth, it would be great to see this feature in the iOS version of FreeOTP, to meet the needs of users in all these circumstances.

**Comment by emmahsax** [comment] 2021-11-03 21:11
I agree completely with this feature. We need to have this capability. I am looking to switch to a different 2FA provider, and I cannot even consider FreeOTP without being able to manually add secret keys, as that's how I add all of my 2FA tokens.

**Comment by justin-stephenson** [comment] 2021-11-04 13:15
Thanks for the feedback, this is a feature I am planning to add back when time permits - also PRs are welcome.

**Comment by emmahsax** [comment] 2021-11-04 14:11
I tried looking for the pull request that removed this functionality, but I couldn't find it. Something tells me it's was merged as _part_ of another pull request.

**Comment by justin-stephenson** [comment] 2021-11-04 14:12
> I tried looking for the pull request that removed this functionality, but I couldn't find it. Something tells me it's was merged as _part_ of another pull request.

Not sure about the PR but the commit is https://github.com/freeotp/freeotp-ios/commit/9ed3fdb9605abe657df7220277d103eee091fc14

**Comment by justin-stephenson** [comment] 2022-02-01 04:07
Manual secret entry is still something we want to add back, it is being tracked in duplicate issue https://github.com/freeotp/freeotp-ios/issues/138

**Closed by justin-stephenson** 2022-02-01 04:07 UTC
