### ISSUE TITLE
After confirming touchid the app closes

### ISSUE THREAD

**Issue by Fallenlemon** [freeotp/freeotp-ios#214] opened 2020-11-20 09:36 UTC
This happened after the latest update. When opening a password-protected token the app closes. If I start it again I'm stuck in this same loop. This is quite serious because i need this to/for work.
thanks

**Comment by justin-stephenson** [comment] 2020-11-25 19:47
Could you test and confirm that the following TestFlight build fixes this issue?

https://testflight.apple.com/join/kSkazqq7

**Comment by tstimper** [comment] 2020-11-29 14:19
confirmed, the issue is fixed in the TestFlight build on iOS 14.2 on iPhone SE (2020)

**Comment by justin-stephenson** [comment] 2020-12-02 17:02
> This happened after the latest update. When opening a password-protected token the app closes. If I start it again I'm stuck in this same loop. This is quite serious because i need this to/for work.
> thanks

I reverted the authentication settings that were causing issues and pushed a 2.2.1 release to the app store, please check it.

**Comment by Fallenlemon** [comment] 2020-12-11 08:51
Hi!

I tried it again and it crashed the first time, but worked on the second
attempt. 
Thanks!

**Closed** 2020-12-15 15:56 UTC
