### ISSUE TITLE
selected icon was overwritten

### ISSUE THREAD

**Issue by krugerk** [freeotp/freeotp-ios#180] opened 2020-07-03 08:21 UTC
I had scanned a code, created an entry/token for it in the app. 
During the process, an icon was selected.

Next, I scanned the same code, creating another entry.
During this process, another icon was selected.

After having added the second one, both entries were using the same icon (the latter).

I would expect either 
 a) selected icons to be preserved 
 b) duplicates prevented if not supported

**Comment by justin-stephenson** [comment] 2020-07-07 12:56
Thank you for the report, we can improve the UI and prompt the user about overwriting a duplicate token as mentioned in https://github.com/freeotp/freeotp-ios/issues/7

Closing this as duplicate of https://github.com/freeotp/freeotp-ios/issues/7

**Closed by justin-stephenson** 2020-07-07 12:56 UTC
