### ISSUE TITLE
Serious problem with invalid image-parameter

### ISSUE THREAD

**Issue by pk1234** [freeotp/freeotp-ios#351] opened 2024-05-13 17:44 UTC
If the otpauth-URL contains an invalid image-parameter, for example:
otpauth://totp/ACME:Jon%20Doe?secret=3GPF4SQT5YMF52AX76RGL3TQP7YSNOFY&image=none
then FreeOTP will crash when such a qr-code is scanned.

This seems harmless, but after that has happened, FreeOTP will crash whenever it's started again, so you loose all of your tokens.

And even worse: FreeOTP will even crash after you delete it from your phone and did a fresh reinstall from AppStore. So the invalid URL is cached somewhere even after the app was deleted - strange!

Any ideas how to recover this situation?

Peter

![grafik](https://github.com/freeotp/freeotp-ios/assets/1835508/ed625417-6d3a-4e4d-8147-c3a264347f46)

Do not scan the above qr-code with FreeOTP - you will not be able to use FreeOTP ever again

**Comment by justin-stephenson** [comment] 2024-05-15 19:05
Thank you for reporting this, it is a serious issues. I will investigate a fix.

Duplicate of https://github.com/freeotp/freeotp-ios/issues/340

**Comment by justin-stephenson** [comment] 2024-05-17 15:08
https://github.com/freeotp/freeotp-ios/pull/352 merged, I'll work next on building and pushing a new FreeOTP release to the app store.

**Closed** 2024-05-17 15:07 UTC

**Comment by pk1234** [comment] 2024-05-17 18:28
Thanks very much
Peter
