### ISSUE TITLE
FreeOTP will not run after latest iphone update

### ISSUE THREAD

**Issue by jon2100** [freeotp/freeotp-ios#258] opened 2021-12-16 05:13 UTC
I updated my iPhone Xs from 15.1 to 15.2 *latest update and went to use my FreeOTP and the application goes to start and just has a full screen white with the application icon in the center of the screen, and nothing happens. I removed the app and put it back on and still nothing.

**Comment by Norjek** [comment] 2021-12-16 07:41
Same problem here. This is bad! I can not login to my accounts anymore 🙈

I do have two iPhones with the same behavior as described above. Steps to reproduce:
1. Touch the App Icon on your homescreen
2. The App goes to full screen, showing the app Icon in the middle (screenshot attached)
![Photo_211216-0838_8914](https://user-images.githubusercontent.com/82393307/146328654-32e12c16-a6c1-4862-9bbb-193a496c62cb.png)
.
3. Wait
4. After a while it closes

It is impossible to get to the keys that way. Happens since I've updated to iOS 15.2 on a iPhone 13 Pro Max 256 GB and on a iPhone Xs 64 GB with iOS 15.2
Low power mode on/off makes no difference.

**Comment by avandorp** [comment] 2021-12-16 09:20
According to a colleague giving the app camera permission makes it working again.

**Comment by Norjek** [comment] 2021-12-16 09:41
> According to a colleague giving the app camera permission makes it working again.

Can't confirm, both devices granted Camera & Bluetooth Access to the app (for god's sake know why my 2FA Token App should need these) and it still does not work.

**Comment by avandorp** [comment] 2021-12-16 09:46
Ah, possibly not camera but photos? (I don't have a device to check).

**Comment by Norjek** [comment] 2021-12-16 09:58
### Photos it is. And it is apparently enough to choose "Selected Photos only" and then only select one Photo.

But I don't want that. Seriously... a 2FA Token App should have access to **nothing** Neither mobile data, nor photos, nor bluetooth or camera. I want to enter the damn secret manually. Maybe export my secrets to a encrypted file to import them on the next device would be nice, though... I understand that most services provide QR Codes to scan, therefore the camera permissions.
That is not your fault either, avandorp, I know. It's just frustrating that a security relevant app needs permissions for which I don't see a reason to. Well, all the apps want to have all the permissions nowadays 😅

Anyway, that does the trick and solves, for now, the most urgent matter to be able to re-login to my accounts. I assume this will help jon2100 as well.
Thanks a lot you guys for sorting that out for now! Please send my regards to your colleague too.

I suggest to someone with developer skills to fix that bug anyway. It spooked the hell out of me today...

**Comment by jon2100** [comment] 2021-12-16 14:14
Yes giving access to 1 photo did the trick. 100% agree should not have access, if I want to scan a QR Code, I enable, scan, disable that simple.

**Comment by justin-stephenson** [comment] 2022-01-04 17:12
I was unable to reproduce this issue after upgrading my test iPhone 8 device to iOS 15.2. 

Prior to FreeOTP 2.0, users could select a photo from the photo library to use as a token icon. I suspect this issue only occurs for devices where FreeOTP  contains a token with a photo library icon in their stored tokens. Can someone please confirm this ? That will help me to determine next steps.

**Comment by Norjek** [comment] 2022-01-04 17:26
Yes, indeed. That is the case... Even though the picture is not shown when it is not available on the device (e.g. no longer stored there or not choosen by the "select picture" menu). There is no way to edit an token entry and remove the picture or set a new one, right?

**Comment by justin-stephenson** [comment] 2022-01-04 19:21
Thanks, I was able to reproduce this issue now.

Our current code does not check if photo library access was granted/denied by the user, or not yet granted(https://developer.apple.com/documentation/photokit/phauthorizationstatus). If photo library access is explicitly denied FreeOTP still tries to request an image from the library which generates the error in Xcode:
~~~
2022-01-04 14:12:37.343875-0500 FreeOTP[638:61307] [GatekeeperXPC] Failed to open photo library file:///var/mobile/Media/, Error Domain=com.apple.photos.error Code=41011 "Unauthorized access: client does not have valid TCC authorization" UserInfo={NSLocalizedDescription=Unauthorized access: client does not have valid TCC authorization}
~~~

I'll work on providing a TestFlight build with a fix for this, if access is denied by the user then FreeOTP will no longer attempt to read from the photo gallery, falling back to the default FreeOTP token icon.

**Comment by justin-stephenson** [comment] 2022-01-04 19:24
> Yes, indeed. That is the case... Even though the picture is not shown when it is not available on the device (e.g. no longer stored there or not choosen by the "select picture" menu). There is no way to edit an token entry and remove the picture or set a new one, right?

Correct, currently there is no edit token ability. I would like to add this functionality back, which can use the new Limited Photos API https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app to avoid granting full access to all photos.

**Comment by justin-stephenson** [comment] 2022-01-07 14:19
Hi, for those willing, could you please verify the following 2.3.1 TestFlight build fixes this issue and does not break any other  FreeOTP functionality

https://testflight.apple.com/join/sqNvx9O2

**Comment by jon2100** [comment] 2022-01-09 04:23
> Hi, for those willing, could you please verify the following 2.3.1 TestFlight build fixes this issue and does not break any other FreeOTP functionality
> 
> https://testflight.apple.com/join/sqNvx9O2

I tested and removed the permission to the photo I set as work around. So far all seems well

**Comment by justin-stephenson** [comment] 2022-01-11 13:49
> Hi, for those willing, could you please verify the following 2.3.1 TestFlight build fixes this issue and does not break any other FreeOTP functionality
> 
> https://testflight.apple.com/join/sqNvx9O2

@Norjek @avandorp would you be willing to test  this TestFlight build fixes the issue after setting back the previous non-working Privacy settings?

**Closed** 2022-01-17 14:56 UTC
