### ISSUE TITLE
FreeOTP stuck crashing at startup if name contains certain characters

### ISSUE THREAD

**Issue by markhallm** [freeotp/freeotp-ios#100] opened 2018-02-20 02:37 UTC
# Steps to reproduce

1. Add a new OTP to the application
2. Rename it to "firstname.lastname@example.com (foobar) – TESTING"
3. Make sure the string is long and contains the en dash character ("–"), not a simple hyphen or minus sign
4. Save the edited name

# Actual results

Application crashes and when trying to reopen the application, it keeps crashing every time. You will no longer be able to access your saved OTPs.

# Expected results

The application can handle long names and special characters like the en dash.

**Comment by vsipuli** [comment] 2018-02-20 03:10
Is there any workaround to recover the OTPs after saving a name that triggers this crashing at startup?

**Comment by JamesForman** [comment] 2018-02-27 08:24
This also appears to happen if you add/edit a Unicode character one of the fields.

**Comment by JamesForman** [comment] 2018-02-27 08:32
This is probably a duplicate of #85

**Comment by TBOTO** [comment] 2018-05-15 14:17
I'm having same issue in IOS 11.3.1 iPhone 6S. Now app is in constant start-up crash.

**Comment by antonini** [comment] 2018-05-25 03:13
Same with me!

**Comment by corsch** [comment] 2019-01-02 13:33
Any news about this issue?

**Comment by psychobatic** [comment] 2019-07-28 06:03
I have also triggered this (or a similar bug) by using a name containing a single quotation mark.

Specifically, the name contained “Robert’s”

Using iPad Pro.

**Comment by 2-fast-to-be-seen** [comment] 2019-09-20 16:31
I have same problem too. 

Tried to add a new account with QR. Then the application crashed and when trying to reopen the application, it keeps crashing every time. So.. I'm no longer able to access mysaved OTPs.

**Comment by jasperges** [comment] 2019-10-14 19:46
Any news on this yet? I bumped into the same problem today (renamed an a account to a name with an 'ë' in it) and now I can't launch the app.

Is there any way to get around the problem or somehow remove the offending account?

**Comment by einar-io** [comment] 2019-10-28 18:20
I experience this issue too.

**Comment by Zeuh** [comment] 2019-11-06 09:28
Crash on Iphone with IOS after scanning Code contains "é" character in issuer name. 

After Crash, impossible to reopen App. we have to uninstall the app to recover...

You can generate the issuer string from this PHP line : 
`html_entity_decode('Universit&eacute; Rennes 2', ENT_COMPAT, 'UTF-8')`

- IOS version : 13.1.2
- FreeOTP version : 1.2

**Comment by CoalaJoe** [comment] 2019-11-13 09:32
👍  Dear god. How do I recover my codes?

**Comment by 2-fast-to-be-seen** [comment] 2019-11-29 19:18
My solution was to contact each company-website I had registered a 2FA on, and had it removed. Instead of FreeOTP I now use OTP Auth which have backup: https://cooperrs.de/otpauth.html (if you have IOS/macOS I recommend that). 
If Android try SAASPASS or Yubikey (if that works for you) :)

**Comment by Andi-fr** [comment] 2020-03-27 12:03
Recovery on iOS 13.4:
1) I used iMazing 2.x (free demo) to extract the App"FreeOTP.imazingapp" incl. its contents.
2) I opened the file with 7-zip and browsed to: FreeOTP.imazingapp\Container\Library\Preferences\
3) I opened org.fedorahosted.freeotp.plist in Notepad++ to manually extract my H/TOTP secrets

Hint: use search "otpauth://" and replace "\r\notpauth://" regexp enabled

**Comment by justin-stephenson** [comment] 2020-06-04 14:45
Hi,

Can someone please confirm that this crash is resolved in `FreeOTP v2.0` ?

**Comment by corsch** [comment] 2020-06-04 14:49
I can confirm, that the App won't crash anymore. I kept the App all the years, waiting for this moment :)

**Comment by justin-stephenson** [comment] 2020-06-09 15:53
Please reopen, or open a new issue if this problem occurs in the latest FreeOTP version in the App store. It should be resolved.

**Closed by justin-stephenson** 2020-06-09 15:53 UTC
